Tool-daruda/daruda-frontend

src/App.tsx, src/main.tsx, src/styles/emotion.d.ts, src/styles/theme.ts
- close #13 
<br>
Theme을 세팅했습니다 !
<br>
1.  스타일 파일에서 `import styled from '@emotion/styled';` 선언해주세요
2. 단축어 `scpt`를 통해 빠른 작성이 가능합니다
3. `color: ${({ theme }) => theme.colors.iris1};`
`${({ theme }) => theme.fonts.title_48_b};`  
이런식으로 사용가능합니다 🖐🏻
초기세팅이라 생략하겠습니다 !
=> [Init] Theme 세팅

src/components/common/spacing/Spacing.tsx
- close #22 
<br>
Spacing 컴포넌트 제작했습니다.
<br>
예를 들어 0.4rem의 여백이 필요할 때 아래처럼 사용해주세요!
```tsx
<Spacing size={0.4} />
```
<br>
Space를 선언하는 컴포넌트라 캡처는 생략하겠습니다.
=> [Feat] Spacing 공통 컴포넌트 구현

src/components/layout/Layout.stories.tsx, src/components/layout/MyPageLayout.stories.tsx
- close #42 
<br>
Layout.stories.tsx이랑 MyPageLayout.stories.tsx 스토리북에서 헤더 푸터 사이에 간격이 있도록 파일 수정했습니다.
<br>
storybook 작성 수정할 부분이나 헤더, 푸터 관련 수정사항 더 있으면 알려주세요!!
<br>
=> [Fix] layout 스토리북 수정

src/components/common/chip/Chip.stories.tsx, src/components/common/chip/Chip.styled.ts, src/components/common/chip/chipColors.ts
- close #47 
<br>
- 칩 컴포넌트 컬러를 알맞게 변경했습니다
<br>
마이페이지 툴 카드 컴포넌트에 자동으로 적용되어서 따로 작업하지 않았습니다!
<br>
=> [Design/#47] Chip 컴포넌트 변경사항 적용

src/components/common/banner/ToolListBanner.styled.ts, src/components/common/banner/ToolListBanner.tsx, src/components/common/chip/Chip.styled.ts, src/pages/community/Community.style.ts, src/pages/community/Community.tsx
- close #55 
<br>
1. `ToolListBanner` 를 가져와서 배치했습니다! 
높이 확장 관련해서는 조금더 생각을 같이 해봐주시면 너무 행복할 것 같습니다 ㅠㅠ
<br>
늘어나라 높이높이... 다 같이 도전해볼까요... 너무 고마워요 
<br>
=> [Feat] 커뮤니티 목록 페이지 VIEW 

src/components/common/modal/AlertModal.tsx, src/components/common/modal/AlterModal.stories.tsx, src/components/common/modal/AlterModal.styled.ts, src/components/common/modal/component/DoubleModal.tsx, src/components/common/modal/component/ModalBtns.tsx, src/components/common/modal/component/ModalWrapper.tsx
- close #72 
<br>
모달 구조를 좀 바꿨습니다!
primary 구조!
<br>
제가 작업해놓고 깜빡하고 PR을 안올렸네여...ㅎㅎㅎㅎㅎ
크기를 피그마 에서 틀 잡힌거를 보고 구현했는데  이상할수도. 있어요...
계속 상황에 맞게 크기가 달라질 수도.............
꼼꼼한 체크 부탁드러용
<br>
=> [Feat] 모달 수정

src/pages/toolDetail/components/community/Community.stories.tsx, src/pages/toolDetail/components/community/Community.styled.ts, src/pages/toolDetail/components/community/Community.tsx
- close #86 
<br>
툴 상세보기에 들어갈 커뮤니티 컴포넌트 구현하였습니다
<br>
<br>
스토리북 참고 !! `ToolDetailCommunityCard`
=> [Feat] 툴 상세보기에 들어갈 커뮤니티 구현

src/components/common/button/circleButton/CircleButton.styled.ts, src/components/common/button/squareButton/SquareButton.styled.ts, src/components/common/chip/Chip.styled.ts, src/pages/toolDetail/components/toggle/Toggle.tsx
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX189DQLvP0vykJKqJnyU4K3LOKcwZB2CAQ%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=p8l3cVd)
- close #90 
<br>
칩 툴 키워드, 버튼 line-height 1로 지정했어여
<br>
<br>
=> [Fix] line height 조정

src/assets/svgs/BtnWritingChipx56.tsx, src/assets/svgs/IcAddimgGray344.tsx, src/assets/svgs/IcArrowRightGray20.tsx, src/assets/svgs/IcLeftarrow60.tsx, src/assets/svgs/IcWatchWhite40.tsx, src/assets/svgs/ImgDarudalogo50.tsx, src/assets/svgs/ImgPopupDelete84.tsx, src/assets/svgs/ImgPopupLogout84.tsx, src/assets/svgs/ImgPopupLogoutcheck84.tsx, src/assets/svgs/ImgPopupQuit84.tsx, src/assets/svgs/ImgPopupWithdrawal84.tsx, src/assets/svgs/ImgTextlogo177.tsx, src/assets/svgs/UnionCopy.tsx, src/pages/toolDetail/components/breadcrumb/BreadCrumb.stories.tsx, src/pages/toolDetail/components/sidewing/Sidewing.stories.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18z2qnlIl7lb3aHKFa9cNAUp1yrFSJwpD8%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=HUARfqQ)
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18sNvAM9RoJ2RFIzIGJKsm2dAdYCG4I2I%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=mAoPBPo)
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1DgMKPAeSHAva3Ih3EclT1UMMB6gOcgTc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Sq4CUzq …
=> Fix/#95: build 에러 해결

src/components/common/banner/ToolListBanner.styled.ts, src/components/common/header/Header.styled.ts, src/components/common/header/Header.tsx, src/pages/intro/Intro.tsx, src/routes/Router.tsx
- close #97 
<br>
온보딩 페이지에서 내부 요소에 대해 Layout 을 해당 페이지에서 제외하고 랜더링합니다
커뮤니티 페이지의 툴 리스트바가 간격을 피그마의 수치와 같게 수정합니다. 
<br>
딱히 없습니다! 
<br>
=> [Fix] 온보딩 페이지 스크롤 이슈 & 커뮤니티 페이지 툴 리스트바 간격 조정

src/components/common/postCard/PostCard.styled.ts, src/components/common/postCard/PostCard.tsx, src/pages/CommunityDetail/CommunityDetail.styled.ts, src/pages/CommunityDetail/CommunityDetail.tsx, src/pages/CommunityDetail/components/comment/commentBoard/CommentBoard.styled.ts, src/pages/CommunityDetail/components/comment/commentBoard/CommentBoard.tsx, src/pages/CommunityDetail/components/comment/commentCard/CommentCard.styled.ts, src/pages/CommunityDetail/components/comment/commentCard/CommentCard.tsx, src/pages/CommunityDetail/components/input/commentInput/CommentInput.styled.ts, src/pages/CommunityDetail/components/input/commentInput/CommentInput.tsx
- close #103 
<br>
1. 게시글 내부 사진, 자세히 보기를 연결했습니다. 
2. 댓글 내부 사진, 자세히 보기를 연결했습니다. 
3. 댓글 작성 부분 사진 링크, 자세히 보기를 연결했습니다. 
4. 커뮤니티 상세 페이지 디자인 QA 를 반영했습니다! 
<br>
커뮤니티 목록보기에는 사진 자세히 보기가 없어서 이부분은 자세히 보기를 넣지 않았습니다! 
<br>
=> [Feat] 이미지 자세히 보기 연결

.storybook/provider.tsx, .stylelintrc.json, src/components/common/header/Header.styled.ts, src/components/common/header/category/Category.styled.ts, src/components/common/header/category/Category.tsx, src/components/common/header/category/apis/api.ts, src/components/common/header/category/apis/queries.ts, src/components/common/header/category/types/index.ts
- close #118 
<br>
- 툴 카테고리 조회 API 연결
- 온보딩 페이지 헤더 그림자 설정
<br>
api 연결 코드 제대로 작성되었는지 확인 부탁해용
<br>
=> [Feat] Header 카테고리 구현 및 UI 수정

src/pages/myPage/MyFavoritePostPage.tsx, src/pages/myPage/MyInfoPage.tsx, src/pages/myPage/MyPostPage.tsx, src/pages/myPage/Post.styled.ts, src/pages/myPage/apis/api.ts, src/pages/myPage/components/affiliationButton/AffiliationBtn.styled.ts, src/pages/myPage/components/namingInput/NamingInput.tsx, src/pages/myPage/components/postCard/PostCard.styled.ts, src/pages/myPage/components/toolCard/MyToolCard.styled.ts, src/pages/myPage/types/info.ts
- close #126 
<br>
마이페이지 뷰 QA 반영
<br>
QA 사항 반영했어요
<br>
=> [Feat] 마이페이지 뷰 QA 반영

src/pages/toolList/ToolList.styled.ts, src/pages/toolList/components/toolCard/ToolCard.styled.ts, src/pages/toolList/components/toolCard/ToolCard.tsx, src/pages/toolList/types/ToolListType.ts
- close #131 
<br>
툴 리스트 북마크 api 연결
<br>
<br>
=> [Feat] ToolList BookMark API 연결

src/components/common/banner/ToolListBanner.styled.ts, src/pages/communityWrite/CommunityWrite.styled.ts, src/pages/communityWrite/components/writingBody/WritingBody.styled.ts, src/pages/communityWrite/components/writingImg/WritingImg.styled.ts, src/pages/communityWrite/components/writingTitle/WritingTitle.styled.ts
- close #133 
<br>
글쓰기 페이지 QA 반영
<br>
<br>
=> [Feat] 글쓰기 페이지 QA 반영

src/components/common/header/Header.tsx, src/components/layout/Layout.stories.tsx, src/components/layout/Layout.tsx, src/components/layout/MyPageLayout.tsx, src/pages/CommunityDetail/CommunityDetail.stories.tsx, src/pages/community/Community.stories.tsx, src/pages/communityModify/CommunityModify.tsx, src/pages/communityModify/components/writingImg/WritingImg.tsx, src/pages/communityModify/utils/FormDataUtils.ts, src/pages/communityWrite/components/writingImg/WritingImg.tsx, src/pages/error/NotFound.stories.tsx, src/pages/intro/Intro.tsx, src/pages/login/KakaoAuth.stories.tsx, src/pages/myPage/MyFavoritePostPage.tsx, src/pages/myPage/MyPostPage.tsx, src/pages/myPage/MyToolPage.tsx, src/pages/myPage/components/postCard/PostCard.tsx, src/pages/myPage/components/toolCard/MyToolCard.tsx, src/pages/myPage/stories/FavoritePostPage.stories.tsx, src/pages/myPage/stories/FavoriteToolPage.stories.tsx, src/pages/myPage/stories/MyInfoPage.stories.tsx, src/pages/myPage/stories/MyPostPage.stories.tsx, src/pages/signUp/SignUp.stories.tsx, src/pages/toolDetail/ToolDetail.stories.tsx, src/pages/toolDetail/ToolDetail.tsx, src/pages/toolDetail/components/referenceVideo/ReferenceVideo.stories.tsx, src/pages/toolDetail/components/referenceVideo/ReferenceVideo.tsx, src/pages/toolDetail/components/referenceVideo/videoCard/VideoCard.stories.ts, src/pages/toolDetail/components/referenceVideo/videoCard/VideoCard.styled.ts, src/pages/toolDetail/components/referenceVideo/videoCard/VideoCard.tsx
=> [Fix] 자잘자잘한 에러 해결

src/pages/toolDetail/components/referenceVideo/videoCard/VideoCard.tsx
=> [Fix] 이미지 썸네일 수정

src/pages/toolDetail/components/breadcrumb/BreadCrumb.tsx
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19QDqnM8BexAs7y2JRb4KysX5kf0KVHM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=nDydnz7)
- close #
<br>
<br>
<br>
=> [Fix] url 영어로 매칭

src/pages/myPage/components/postCard/PostCard.tsx, src/pages/myPage/components/toolCard/MyToolCard.tsx
=> [Fix] 마이페이지 부모 클릭 이벤트 전파 해결

src/apis/tool/getToolData.ts, src/apis/tool/queries.ts, src/pages/CommunityDetail/CommunityDetail.tsx, src/pages/CommunityDetail/apis/fetchDetailPost/api.ts, src/pages/CommunityDetail/apis/fetchDetailPost/queries.ts, src/pages/toolDetail/ToolDetail.tsx, yarn.lock
=> [Feat] 서버 응답 404 렌더링

src/pages/community/Community.tsx, src/pages/toolList/ToolList.styled.ts, src/pages/toolList/ToolList.tsx
=> [Fix] 툴 리스트 오류 수정

src/components/common/banner/ToolListBanner.tsx, src/pages/myPage/components/tab/MyPageTab.tsx
=> [Fix] 1차 에러 해결

src/apis/board/api.ts, src/components/common/postCard/PostCard.tsx, src/pages/CommunityDetail/apis/deletePost/api.ts, src/pages/CommunityDetail/apis/postComment/api.ts, src/pages/CommunityDetail/apis/postComment/queries.ts, src/pages/CommunityDetail/components/comment/commentCard/CommentCard.tsx, src/pages/CommunityDetail/components/input/commentInput/CommentInput.tsx, src/pages/CommunityDetail/constants/index.ts, src/pages/CommunityDetail/hooks/useImageUpload.ts, src/pages/CommunityDetail/hooks/useToastOpen.ts, src/pages/community/Community.tsx
- close #157 
<br>
커뮤니티 비회원시 비활성화!! 
비회원시 특정 기능 막기
커뮤니티 리스트 목록 클릭시 바닥을 보고 있음
댓글 이미지 자세히 보기 클릭시, 토스트 팝업 뜨는 오류 를 해결했습니다!! 
<br>
없어요잇! 
<br>
=> [Fix] QA 반영 사항 커뮤니티 오류 해결 

src/apis/board/queries.ts, src/components/common/postCard/PostCard.tsx
=> [Fix] 게시글 스크랩 이슈 해결

src/pages/toolList/components/topBanner/TopBanner.styled.ts, src/pages/toolList/components/topBanner/TopBanner.tsx
- close #169 
<br>
툴 리스트 페이지 상단의 배너 배경 색상 `black` 추가
<br>
<br>
=> [Design] 배너 색상 추가

src/pages/communityWrite/CommunityWrite.tsx, src/pages/myPage/MyFavoritePostPage.tsx, src/pages/myPage/MyInfoPage.tsx, src/pages/myPage/MyPostPage.tsx, src/pages/myPage/MyToolPage.tsx, src/pages/myPage/apis/queries.ts
=> [Fix] 마이페이지 토스트 수정

src/components/common/toast/Toast.styled.ts, src/components/common/toast/Toast.tsx, src/pages/toolList/components/toolCard/ToolCard.tsx
- close #181 
<br>
툴 리스트 페이지에서 북마크시, 북마크가 잘 담겼음을 나타내는 토스트 팝업 뜨도록 했습니다. 
북마크가 된 경우, 북마크 취소한 경우를 나눠서 처리했습니다. 
<br>
QA에 올라온 건 처리했는데, 하다보니 탄스택 쿼리 붙이는 과정에서 다 바뀔 것 같다는 생각이 드네요.
무한스크롤이다보니 생각보다 상태관리하고 있는게 많아서, 팝업 붙이면서 `InfiniteQuery` 작업할까 하다가 일단 이슈 내용대로만 올려봅니다! 
같은 이슈에서 처리하기엔 조금 작업이 많아서 고민이 되긴 하는뎀 다들 괜찮으시다면 다음 이슈에서 처리해도 될까요?!
<br>
정상작동 되는거 확인했습니다!
=> [Feat] 북마크시 토스트 팝업이 뜨도록 설정한다 

src/pages/login/apis/postKakaoToken.ts
최신화된 백엔드 문서에 맞춰 헤더 부분을 수정하였습니다. 
<br>
딱히 없습니다! 
<br>
헤더와 관련된 부분이기에 생략하겠습니다!
=> [!HOTFIX] 로그인 token API 부분 헤더를 정정한다.

src/pages/login/KakaoRedirectHandler.tsx, src/pages/login/apis/postKakaoToken.ts
=> [Fix] 카카오 로그인을 정상화한다. 

src/components/common/input/nameInput/NameInput.tsx
- close #206 
<br>
한글, 숫자, 영어만 입력 가능하도록 바꿨습니다.
<br>
<br>
=> [Feat] 마이페이지 닉네임 특수문자 입력을 제한한다.

src/apis/auth/auth.api.ts, src/apis/index.ts
- close #227 
<br>
- response의 data 참조를 알맞게 변경했습니다.
- reissue가 실패할 경우 로그인으로 리다이렉트되도록 변경했습니다.
<br>
<br>
- 액세스발급 성공했을 경우
https://github.com/user-attachments/assets/899b8a04-d196-4ed5-b72c-0ebe252a4470
- 리프레시 토큰도 만료됐을 경우
https://github.com/user-attachments/assets/36e59978-1a96-457f-af79-07abbdc332f8
=> [Fix] 액세스토큰 재발급 로직을 수정한다.
